[nixpkgs]
src.git = "https://github.com/NixOS/nixpkgs"
src.branch = "nixos-unstable"
fetch.tarball = "https://github.com/NixOS/nixpkgs/archive/$ver.tar.gz"

[preservation]
src.git = "https://github.com/nix-community/preservation"
fetch.tarball = "https://github.com/nix-community/preservation/archive/$ver.tar.gz"

[hjem]
src.git = "https://github.com/feel-co/hjem"
fetch.tarball = "https://github.com/feel-co/hjem/archive/$ver.tar.gz"

[sops-nix]
src.git = "https://github.com/Mic92/sops-nix"
fetch.tarball = "https://github.com/Mic92/sops-nix/archive/$ver.tar.gz"

[nix-index-database]
src.git = "https://github.com/nix-community/nix-index-database"
fetch.tarball = "https://github.com/nix-community/nix-index-database/archive/$ver.tar.gz"

[neovim-config]
src.git = "https://git.gay/sunworms/neovim-config"
fetch.tarball = "https://git.gay/sunworms/neovim-config/archive/$ver.tar.gz"

# binary packages
[pcsx2]
src.cmd = "curl -sL 'https://api.github.com/repos/PCSX2/pcsx2/releases?per_page=1' | grep -oP '\"tag_name\":\\s*\"\\K[^\"]+'"
src.prefix = "v"
fetch.url = "https://github.com/PCSX2/pcsx2/releases/download/v$ver/pcsx2-v$ver-linux-appimage-x64-Qt.AppImage"

[eden]
src.webpage = "https://nightly.eden-emu.dev/latest/release.json"
src.regex = 'v\d+\.[0-9a-f]+'
src.from_pattern = 'v(\d+)\.([a-f0-9]+)'
src.to_pattern = 'v\1.\2/Eden-Linux-\2'
fetch.url = "https://nightly.eden-emu.dev/$ver-amd64-clang-pgo.AppImage"

[helium]
src.github = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64_linux.tar.xz"

[iosevka-custom]
src.github = "sunworms/iosevka-nerd"
src.prefix = "v"
fetch.url = "https://github.com/sunworms/iosevka-nerd/releases/download/v$ver/Iosevka-Custom-v$ver.zip"

[tuigreet]
src.github = "NotAShelf/tuigreet"
fetch.url = "https://github.com/NotAShelf/tuigreet/releases/download/$ver/tuigreet-$ver-x86_64"
