[shorturls]
gh = "github:{path}"
nixpkgs = "https://channels.nixos.org/{path}/nixexprs.tar.xz"

[all_follow]
nixpkgs = ["nixpkgs", "nixpkgs-lib"]

[inputs.nixpkgs]
url = "nixpkgs:nixos-unstable"
type = "fetch"

[inputs.preservation]
url = "gh:nix-community/preservation"
type = "fetch"

[inputs.hjem]
url = "gh:feel-co/hjem"
type = "fetch"

[inputs.neovim-config]
url = "git+https://git.gay/sunworms/neovim-config"
type = "fetch"

[inputs.sops-nix]
url = "gh:Mic92/sops-nix"
type = "fetch"

[inputs.niri-nix]
url = "git+https://codeberg.org/BANanaD3V/niri-nix"
type = "fetch"

[inputs.noctalia]
url = "gh:noctalia-dev/noctalia"
type = "fetch"

[inputs.watt]
url = "gh:NotAShelf/watt"
type = "fetch"

[inputs.niri-float-sticky]
url = "gh:probeldev/niri-float-sticky"
type = "fetch"
