# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agenix = {
    pname = "agenix";
    version = "07a33319a408a0c770f0fe5d0d98f5e7b4e5a5e7";
    src = fetchTarball {
      url = "https://github.com/ryantm/agenix/archive/07a33319a408a0c770f0fe5d0d98f5e7b4e5a5e7.tar.gz";
      sha256 = "sha256-dLq4qfJvm2ZfkwGGdgWl/nsA2aavpQMrPQbNqbkLXKE=";
    };
    date = "2026-09-26";
  };
  eden = {
    pname = "eden";
    version = "v1790369717.bebc19da32/Eden-Linux-bebc19da32";
    src = fetchurl {
      url = "https://nightly.eden-emu.dev/v1790369717.bebc19da32/Eden-Linux-bebc19da32-amd64-gcc-standard.AppImage";
      sha256 = "sha256-40otBPqoS1Vl6eF/iaHjRmgZhitGUQPX5HtohD8Rsns=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.18.1.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.18.1.1/helium-0.18.1.1-x86_64_linux.tar.xz";
      sha256 = "sha256-n001I57qGLKQhGIhh0JlrCqGN63/lU32n973fWsVBCw=";
    };
  };
  hjem = {
    pname = "hjem";
    version = "cef02450f2c18a7e2b9297ea8d366f9a597254f7";
    src = fetchTarball {
      url = "https://github.com/feel-co/hjem/archive/cef02450f2c18a7e2b9297ea8d366f9a597254f7.tar.gz";
      sha256 = "sha256-tycoVCB2KSVdy9ERT1lJGHdP9Hf4FHanaEY25hUxylw=";
    };
    date = "2026-09-22";
  };
  neovim-config = {
    pname = "neovim-config";
    version = "2e52d08f266e87186159f1bf8598a2ec18cfa030";
    src = fetchTarball {
      url = "https://git.gay/sunworms/neovim-config/archive/2e52d08f266e87186159f1bf8598a2ec18cfa030.tar.gz";
      sha256 = "sha256-i/256SKf4g1yjys8DbliUmtuk1knjZEYMEfvoaZBei0=";
    };
    date = "2026-09-26";
  };
  niri-nix = {
    pname = "niri-nix";
    version = "926ca86fab82738fd1461b022ee11b4d61b9bf2e";
    src = fetchTarball {
      url = "https://codeberg.org/BANanaD3V/niri-nix/archive/926ca86fab82738fd1461b022ee11b4d61b9bf2e.tar.gz";
      sha256 = "sha256-vE1BM9nWfusQ437QX9beTLhs5S2zAvdlmnrT9XYbacs=";
    };
    date = "2026-09-26";
  };
  nix-index-database = {
    pname = "nix-index-database";
    version = "9ad722673ab3b3f91f02135e53775825b240b869";
    src = fetchTarball {
      url = "https://github.com/nix-community/nix-index-database/archive/9ad722673ab3b3f91f02135e53775825b240b869.tar.gz";
      sha256 = "sha256-Dkg4VKPmDPqTwaiw2WH5br73tXoL1qrOO0xJnR4TlcA=";
    };
    date = "2026-09-20";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "e94cb152ed51bd6e24eb4a41f1460252beb52cd2";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/e94cb152ed51bd6e24eb4a41f1460252beb52cd2.tar.gz";
      sha256 = "sha256-VVTPf+Hyd5ebpjBMHmrLMSBIeW6ls48Bqtosj7CNKLA=";
    };
    date = "2026-09-25";
  };
  nsticky = {
    pname = "nsticky";
    version = "v0.4.0";
    src = fetchTarball {
      url = "https://github.com/lonerOrz/nsticky/archive/v0.4.0.tar.gz";
      sha256 = "sha256-ysKHQwPbiPFYUzAbewYKUF3o2IAjR3Jt2a6uBgqRgGU=";
    };
  };
  pcsx2 = {
    pname = "pcsx2";
    version = "2.9.88";
    src = fetchurl {
      url = "https://github.com/PCSX2/pcsx2/releases/download/v2.9.88/pcsx2-v2.9.88-linux-appimage-x64-Qt.AppImage";
      sha256 = "sha256-Jg1TneHMRtHo7/LNQeQU0yb3IuJBhgVFAgMFsJV2CCM=";
    };
  };
  preservation = {
    pname = "preservation";
    version = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
    src = fetchTarball {
      url = "https://github.com/nix-community/preservation/archive/93416f4614ad2dfed5b0dcf12f27e57d27a5ab11.tar.gz";
      sha256 = "sha256-mMI9IanU+Xw+pVogD2oT0I2kTmvz2Un/Apc5+CwUpEY=";
    };
    date = "2025-09-09";
  };
}
