# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agenix = {
    pname = "agenix";
    version = "b027ee29d959fda4b60b57566d64c98a202e0feb";
    src = fetchTarball {
      url = "https://github.com/ryantm/agenix/archive/b027ee29d959fda4b60b57566d64c98a202e0feb.tar.gz";
      sha256 = "sha256-9VnK6Oqai65puVJ4WYtCTvlJeXxMzAp/69HhQuTdl/I=";
    };
    date = "2026-02-03";
  };
  eden = {
    pname = "eden";
    version = "v1789934660.a277b62fe4/Eden-Linux-a277b62fe4";
    src = fetchurl {
      url = "https://nightly.eden-emu.dev/v1789934660.a277b62fe4/Eden-Linux-a277b62fe4-amd64-gcc-standard.AppImage";
      sha256 = "sha256-cT2jsIV7wXqMDywevtzxyq5LBkDcGlqf2M8Wbmb5pd4=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.17.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.17.2.1/helium-0.17.2.1-x86_64_linux.tar.xz";
      sha256 = "sha256-KmOd9U49BfQTz7tGIqTRpoWEsx2lp6r1juPNg8fD4pk=";
    };
  };
  hjem = {
    pname = "hjem";
    version = "cef02450f2c18a7e2b9297ea8d366f9a597254f7";
    src = fetchTarball {
      url = "https://github.com/feel-co/hjem/archive/cef02450f2c18a7e2b9297ea8d366f9a597254f7.tar.gz";
      sha256 = "sha256-tycoVCB2KSVdy9ERT1lJGHdP9Hf4FHanaEY25hUxylw=";
    };
    date = "2026-09-22";
  };
  neovim-config = {
    pname = "neovim-config";
    version = "02f0c389ac81ecb51f69678f01b7d9fa6a61f243";
    src = fetchTarball {
      url = "https://git.gay/sunworms/neovim-config/archive/02f0c389ac81ecb51f69678f01b7d9fa6a61f243.tar.gz";
      sha256 = "sha256-ZB7VUWKllLBcYcVaZfwaKgdFn3Z1MdxdEKne+2bPpYo=";
    };
    date = "2026-09-23";
  };
  niri-nix = {
    pname = "niri-nix";
    version = "14cba846642f28987bf187a2dec8980f965e24a3";
    src = fetchTarball {
      url = "https://codeberg.org/BANanaD3V/niri-nix/archive/14cba846642f28987bf187a2dec8980f965e24a3.tar.gz";
      sha256 = "sha256-vjrUXZvCLzgGOaHnBWID4Y59Gw2DCa3Du/dUTwF8t8g=";
    };
    date = "2026-09-23";
  };
  nix-index-database = {
    pname = "nix-index-database";
    version = "9ad722673ab3b3f91f02135e53775825b240b869";
    src = fetchTarball {
      url = "https://github.com/nix-community/nix-index-database/archive/9ad722673ab3b3f91f02135e53775825b240b869.tar.gz";
      sha256 = "sha256-Dkg4VKPmDPqTwaiw2WH5br73tXoL1qrOO0xJnR4TlcA=";
    };
    date = "2026-09-20";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "6774f7bc253789b113a4f39285dc0fa100abeacc";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/6774f7bc253789b113a4f39285dc0fa100abeacc.tar.gz";
      sha256 = "sha256-MYiI+CzL0tuWgRPjGsKCDHqYs2T3OzMlMQWOYWG0qso=";
    };
    date = "2026-09-22";
  };
  nsticky = {
    pname = "nsticky";
    version = "v0.4.0";
    src = fetchTarball {
      url = "https://github.com/lonerOrz/nsticky/archive/v0.4.0.tar.gz";
      sha256 = "sha256-ysKHQwPbiPFYUzAbewYKUF3o2IAjR3Jt2a6uBgqRgGU=";
    };
  };
  pcsx2 = {
    pname = "pcsx2";
    version = "2.9.79";
    src = fetchurl {
      url = "https://github.com/PCSX2/pcsx2/releases/download/v2.9.79/pcsx2-v2.9.79-linux-appimage-x64-Qt.AppImage";
      sha256 = "sha256-FwZQjFRzCiFCHUKJJ83+tTSE/tGGICtphvvF33D1PN0=";
    };
  };
  preservation = {
    pname = "preservation";
    version = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
    src = fetchTarball {
      url = "https://github.com/nix-community/preservation/archive/93416f4614ad2dfed5b0dcf12f27e57d27a5ab11.tar.gz";
      sha256 = "sha256-mMI9IanU+Xw+pVogD2oT0I2kTmvz2Un/Apc5+CwUpEY=";
    };
    date = "2025-09-09";
  };
}
