# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  eden = {
    pname = "eden";
    version = "v1785092351.39763e7321/Eden-Linux-39763e7321";
    src = fetchurl {
      url = "https://nightly.eden-emu.dev/v1785092351.39763e7321/Eden-Linux-39763e7321-amd64-clang-pgo.AppImage";
      sha256 = "sha256-ZH34oXpPQDLBgKZk0uel9RnLbazhO7XFMdNq4KB3qWw=";
    };
  };
  pcsx2 = {
    pname = "pcsx2";
    version = "v2.7.494";
    src = fetchurl {
      url = "https://github.com/PCSX2/pcsx2/releases/download/v2.7.494/pcsx2-v2.7.494-linux-appimage-x64-Qt.AppImage";
      sha256 = "sha256-aSRe/HPrLp++oSxIY1xJixcXHfUSEFa0kFEiILxGgrA=";
    };
  };
}
