# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8fe209bb-6ba5-483e-bf06-72dec51b4df6";
      fsType = "btrfs";
      options = [ "compress=zstd:5" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/749c5a32-fa8c-4eb4-9830-b4924dd5a51d";
      fsType = "btrfs";
      options = [ "compress=zstd:5" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0B8E-D680";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5b8be120-fd30-491b-abd3-a676ce48b1db"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
