-- Generated by Hellwal (Base16 Template)

require('base16-colorscheme').setup({
  base00 = "#%% background.hex %%", -- Default Background
  base01 = "#%% color0.hex %%",     -- Lighter Background (Used for status bars)
  base02 = "#%% color8.hex %%",     -- Selection Background
  base03 = "#%% color8.hex %%",     -- Comments, Invisibles, Line Highlighting
  base04 = "#%% color7.hex %%",     -- Dark Foreground (Used for status bars)
  base05 = "#%% foreground.hex %%", -- Default Foreground, Caret, Delimiters, Operators
  base06 = "#%% color15.hex %%",    -- Light Foreground
  base07 = "#%% color15.hex %%",    -- Lightest Foreground

  base08 = "#%% color1.hex %%",     -- Variables, XML Tags, Markup Link Text
  base09 = "#%% color3.hex %%",     -- Integers, Boolean, Constants, XML Attributes
  base0A = "#%% color11.hex %%",    -- Classes, Markup Bold, Search Text Background
  base0B = "#%% color2.hex %%",     -- Strings, Inherited Class, Markup Code
  base0C = "#%% color6.hex %%",     -- Support, Regular Expressions, Escape Characters
  base0D = "#%% color4.hex %%",     -- Functions, Methods, Attribute IDs, Headings
  base0E = "#%% color5.hex %%",     -- Keywords, Storage, Selector, Markup Italic
  base0F = "#%% color13.hex %%",    -- Deprecated, Opening/Closing Embedded Tag Tags
})

-- Additional Highlight Fixes

local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Selection Highlight
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#%% color4.hex %%',
  fg = '#%% background.hex %%',
})

-- Strings
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#%% color2.hex %%',
})

-- Comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#%% color8.hex %%',
  italic = true,
})

-- Methods & Functions
set_hl_mutliple({ 'TSMethod', 'Method', 'TSFunction', 'Function' }, {
  fg = '#%% color4.hex %%',
})

-- Keywords
set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#%% color5.hex %%',
})
