background {
  monitor =
  path = ~/nixos-files/assets/walls/perlamutrovie.png
  blur_passes = 2
  blur_size = 5
}

input-field {
  monitor =
  size = 20%, 5%
  font_family = Noto Sans
  dots_size = 0.08
  font_color = rgba(6, 29, 42, 0.9)
  outer_color = rgba(6, 29, 42, 0.9)
  inner_color = rgba(112, 217, 177, 0.9)
}

label {
  monitor =
  text = $TIME
  font_size = 50
  position = 0, 80
}