;; Meow mode
(require 'meow)
(setq meow-use-clipboard t)
(setq meow-leader-key "SPC")

(keymap-global-set "<escape>" #'keyboard-escape-quit)
(setq meow-cancel-selection-on-change t)

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore))
  
  (meow-leader-define-key
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)
   
   '("f f" . find-file)
   '("f s" . save-buffer)
   '("f r" . recentf-open-files)
   '("f t" . treemacs)

   '("s s" . isearch-forward)
   '("s r" . query-replace)

   '("SPC" . execute-extended-command)

   '("q q" . save-buffers-kill-terminal)
   '("q r" . restart-emacs)

   '("w v" . split-window-right)
   '("w s" . split-window-below)
   '("w d" . delete-window)
   '("w o" . delete-other-windows)

   '("w h" . windmove-left)
   '("w j" . windmove-down)
   '("w k" . windmove-up)
   '("w l" . windmove-right)

   '("w H" . shrink-window-horizontally)
   '("w L" . enlarge-window-horizontally)
   '("w J" . shrink-window)
   '("w K" . enlarge-window)

   '("b b" . switch-to-buffer)
   '("b n" . next-buffer)
   '("b p" . previous-buffer)
   '("b k" . kill-current-buffer)
   '("b r" . revert-buffer)

   '("t n" . tab-bar-new-tab)
   '("t k" . tab-bar-close-tab)
   '("t l" . tab-bar-switch-to-next-tab)
   '("t h" . tab-bar-switch-to-prev-tab)
   '("t r" . tab-bar-rename-tab)

   '("p f" . project-find-file)
   '("p b" . project-switch-to-buffer)
   '("p k" . project-kill-buffers)
   '("p s" . project-shell)))

(defun my/meow-minibuffer-setup ()
  (meow-insert-mode))

(add-hook 'minibuffer-setup-hook
          #'my/meow-minibuffer-setup)

(meow-setup)

(meow-global-mode 1)
