# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  atomic-chrome = {
    pname = "atomic-chrome";
    version = "344247d45ae19b03751344a4c9ee4c163fc82379";
    src = fetchFromGitHub {
      owner = "KarimAziev";
      repo = "atomic-chrome";
      rev = "344247d45ae19b03751344a4c9ee4c163fc82379";
      fetchSubmodules = false;
      sha256 = "sha256-YP8b1Nkoj7ewmM3IhlUhqvdSxWcEI8MQwJ+UY5QEtz8=";
    };
    date = "2025-10-07";
  };
  eden-nightly = {
    pname = "eden-nightly";
    version = "v0.2.0-rc1";
    src = fetchurl {
      url = "https://git.eden-emu.dev/eden-emu/eden/releases/download/v0.2.0-rc1/Eden-Linux-v0.2.0-rc1-amd64-clang-pgo.AppImage";
      sha256 = "sha256-WB+UcqaW/Gf2STA8E8vCwi6EScPrdSIrje0V5xPW65Q=";
    };
  };
  emacs = {
    pname = "emacs";
    version = "9ba02d512a4f7c5c8a0919ae977e495c47bb6cfa";
    src = fetchgit {
      url = "https://git.gay/sunworms/emacs-config";
      rev = "9ba02d512a4f7c5c8a0919ae977e495c47bb6cfa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Q/n9MklxbGGOKzTr8BlkALEVMDibi50G8awmg6Dh5xw=";
    };
    date = "2026-02-18";
  };
  helium = {
    pname = "helium";
    version = "0.9.2.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.9.2.1/helium-0.9.2.1-x86_64.AppImage";
      sha256 = "sha256-guDBIr8NOD0GtjWznsVXlvb6llvdWHxREfDvXeP4m/w=";
    };
  };
  hjem = {
    pname = "hjem";
    version = "7f2880d705edf541955d98f56cb78f9507384423";
    src = fetchFromGitHub {
      owner = "feel-co";
      repo = "hjem";
      rev = "7f2880d705edf541955d98f56cb78f9507384423";
      fetchSubmodules = false;
      sha256 = "sha256-1RfmXbDIxgwP2/SrYSYd9zdArUaJEm6C3FXpdRlmeso=";
    };
    date = "2026-02-16";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "a82ccc39b39b621151d6732718e3e250109076fa";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "a82ccc39b39b621151d6732718e3e250109076fa";
      fetchSubmodules = false;
      sha256 = "sha256-gf2AmWVTs8lEq7z/3ZAsgnZDhWIckkb+ZnAo5RzSxJg=";
    };
    date = "2026-02-13";
  };
  preservation = {
    pname = "preservation";
    version = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "preservation";
      rev = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
      fetchSubmodules = false;
      sha256 = "sha256-mMI9IanU+Xw+pVogD2oT0I2kTmvz2Un/Apc5+CwUpEY=";
    };
    date = "2025-09-09";
  };
  quickshell = {
    pname = "quickshell";
    version = "dacfa9de829ac7cb173825f593236bf2c21f637e";
    src = fetchFromGitHub {
      owner = "quickshell-mirror";
      repo = "quickshell";
      rev = "dacfa9de829ac7cb173825f593236bf2c21f637e";
      fetchSubmodules = false;
      sha256 = "sha256-ngXnN5YXu+f45+QGYNN/VEBMQmcBCYGRCqwaK8cxY1s=";
    };
    date = "2026-02-09";
  };
  smfh = {
    pname = "smfh";
    version = "dd0a33fc9d1fe7c29da86225af4b4a47b1714839";
    src = fetchFromGitHub {
      owner = "feel-co";
      repo = "smfh";
      rev = "dd0a33fc9d1fe7c29da86225af4b4a47b1714839";
      fetchSubmodules = false;
      sha256 = "sha256-6zMgOPzBbTSm8jzPqmGcotjvkN3HzxcnMM8pW64JpZQ=";
    };
    date = "2026-02-15";
  };
  sops-nix = {
    pname = "sops-nix";
    version = "2d0cf89b4404529778bc82de7e42b5754e0fe4fa";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "sops-nix";
      rev = "2d0cf89b4404529778bc82de7e42b5754e0fe4fa";
      fetchSubmodules = false;
      sha256 = "sha256-UFc4lfGBr+wJmwgDGJDn1cVD6DTr0/8TdronNUiyXlU=";
    };
    date = "2026-02-15";
  };
}
