# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  eden = {
    pname = "eden";
    version = "v1774464339.f0d77e86e3/Eden-Linux-f0d77e86e3";
    src = fetchurl {
      url = "https://github.com/Eden-CI/Nightly/releases/download/v1774464339.f0d77e86e3/Eden-Linux-f0d77e86e3-amd64-clang-pgo.AppImage";
      sha256 = "sha256-KeIrjjY8I3czerQ+gm5DLhKWwb8OIiOUjuvcb9tH57Y=";
    };
  };
  pcsx2 = {
    pname = "pcsx2";
    version = "v2.7.217";
    src = fetchurl {
      url = "https://github.com/PCSX2/pcsx2/releases/download/v2.7.217/pcsx2-v2.7.217-linux-appimage-x64-Qt.AppImage";
      sha256 = "sha256-fvhScJl0SiOq4mieKdqAwJ0cxfQJzLY1LqXrimON5Z4=";
    };
  };
}
