# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  eden-nightly = {
    pname = "eden-nightly";
    version = "v1770404621.b9e052b3a7/Eden-Linux-b9e052b3a7";
    src = fetchurl {
      url = "https://github.com/Eden-CI/Nightly/releases/download/v1770404621.b9e052b3a7/Eden-Linux-b9e052b3a7-amd64-clang-pgo.AppImage";
      sha256 = "sha256-Ht6wtvzIi09uHXSoTyJ6Lp7b75lb97+HUebPhy1zKoI=";
    };
  };
  emacs = {
    pname = "emacs";
    version = "1ff0eff6281e330f1d6b7f2c79b3bddd39652c72";
    src = fetchgit {
      url = "https://git.gay/sunworms/emacs-config";
      rev = "1ff0eff6281e330f1d6b7f2c79b3bddd39652c72";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tyP2oVE1nVP44tYPOxIgjgIERbHZUk4+c+nwVc2wvD4=";
    };
    date = "2026-02-07";
  };
  helium = {
    pname = "helium";
    version = "0.8.5.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.8.5.1/helium-0.8.5.1-x86_64.AppImage";
      sha256 = "sha256-jFSLLDsHB/NiJqFmn8S+JpdM8iCy3Zgyq+8l4RkBecM=";
    };
  };
  hjem = {
    pname = "hjem";
    version = "9d0c8d4b44f661910595b07e6480557644c1431c";
    src = fetchFromGitHub {
      owner = "feel-co";
      repo = "hjem";
      rev = "9d0c8d4b44f661910595b07e6480557644c1431c";
      fetchSubmodules = false;
      sha256 = "sha256-cKETEBrseo7Iz+bOzflwy1xTpDuUj3QaLA+P49yJw8k=";
    };
    date = "2026-01-22";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "00c21e4c93d963c50d4c0c89bfa84ed6e0694df2";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nixpkgs";
      rev = "00c21e4c93d963c50d4c0c89bfa84ed6e0694df2";
      fetchSubmodules = false;
      sha256 = "sha256-AYqlWrX09+HvGs8zM6ebZ1pwUqjkfpnv8mewYwAo+iM=";
    };
    date = "2026-02-04";
  };
  pcsx2 = {
    pname = "pcsx2";
    version = "v2.7.99";
    src = fetchurl {
      url = "https://github.com/PCSX2/pcsx2/releases/download/v2.7.99/pcsx2-v2.7.99-linux-appimage-x64-Qt.AppImage";
      sha256 = "sha256-f130yRsFlQ0gdHs5xocqaeBBeFkV/vVJ7VgBNXw13VM=";
    };
  };
  preservation = {
    pname = "preservation";
    version = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "preservation";
      rev = "93416f4614ad2dfed5b0dcf12f27e57d27a5ab11";
      fetchSubmodules = false;
      sha256 = "sha256-mMI9IanU+Xw+pVogD2oT0I2kTmvz2Un/Apc5+CwUpEY=";
    };
    date = "2025-09-09";
  };
  quickshell = {
    pname = "quickshell";
    version = "1e4d804e7f3fa7465811030e8da2bf10d544426a";
    src = fetchFromGitHub {
      owner = "quickshell-mirror";
      repo = "quickshell";
      rev = "1e4d804e7f3fa7465811030e8da2bf10d544426a";
      fetchSubmodules = false;
      sha256 = "sha256-WW00FaBiUmQyxvSbefvgxIjwf/WmRrEGBbwMHvW/7uQ=";
    };
    date = "2026-01-28";
  };
  sops-nix = {
    pname = "sops-nix";
    version = "17eea6f3816ba6568b8c81db8a4e6ca438b30b7c";
    src = fetchFromGitHub {
      owner = "Mic92";
      repo = "sops-nix";
      rev = "17eea6f3816ba6568b8c81db8a4e6ca438b30b7c";
      fetchSubmodules = false;
      sha256 = "sha256-ktjWTq+D5MTXQcL9N6cDZXUf9kX8JBLLBLT0ZyOTSYY=";
    };
    date = "2026-02-03";
  };
}
