# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.postDeviceCommands = pkgs.lib.mkBefore ''
    mkdir -p /mnt
    mount -o subvol=@root /dev/disk/by-label/root /mnt

    btrfs subvolume list /mnt/@root | cut -f9 -d' ' | while read subvolume; do
      echo "deleting /$subvolume subvolume..."
      btrfs subvolume delete "/mnt/$subvolume"
    done &&

    echo "deleting /@root subvolume..." &&
    btrfs subvolume delete /mnt/@root

    echo "restoring blank /@root subvolume..."
    btrfs subvolume snapshot /mnt/@root-blank /mnt/@root

    umount /mnt
    
    mount -o subvol=@home /dev/disk/by-label/home /mnt

    echo "deleting /@home subvolume..." &&
    btrfs subvolume delete /mnt/@home

    echo "restoring blank /@home subvolume..."
    btrfs subvolume snapshot /mnt/@home-blank /mnt/@home

    umount /mnt
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-label/root";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress-force=zstd:5" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/root";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress-force=zstd:5" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-label/home";
      fsType = "btrfs";
      neededForBoot = true;
      options = [ "subvol=@persist" "compress-force=zstd:5" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/home";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress-force=zstd:5" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
