theme = "matugen"

[editor]
insecure = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys]

[keys.normal]
"C-m" = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"'
"C-p" = ':lsp-workspace-command tinymist.startDefaultPreview'
"A-p" = ':lsp-workspace-command tinymist.doKillPreview "default_preview"'
