theme = "noctalia"

[editor]
insecure = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys]

[keys.normal]
"C-p" = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"'
