theme = "pywal"

[editor]
#bufferline = "multiple" #for official helix
line-number = "relative"
cursorline = true

# only in gj1118/helix
[editor.bufferline]
render-mode = "multiple"
separator = "│"

# only in gj1118/helix
[editor.notifications]
enable = true
style = "statusline"

[editor.workspace-trust]
level = "servers"
prompt = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

# only in gj1118/helix
[editor.auto-reload]
focus-gained = true

[keys]

[keys.normal]
"C-m" = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"'
"C-p" = ':lsp-workspace-command tinymist.startDefaultPreview'
"A-p" = ':lsp-workspace-command tinymist.doKillPreview "default_preview"'

C-left  = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_start", "collapse_selection"]

[keys.insert]
C-left  = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_start", "collapse_selection"]

[keys.select]
C-left  = "extend_prev_word_start"
C-right = "extend_next_word_start"
