# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0489", ATTR{idProduct}=="e111", ATTR{authorized}="0"
  '';

  boot.initrd = {
    availableKernelModules = [
      "xhci_pci"
      "nvme"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    kernelModules = [
      "kvm-intel"
      "intel_vpu"
    ];
    systemd = {
      enable = true;
      services.rollback = {
        description = "Rollback BTRFS root subvolume to a pristine state";
        wantedBy = ["initrd.target"];
        after = ["initrd-root-device.target"];
        before = ["sysroot.mount"];

        unitConfig.DefaultDependencies = "no";

        path = with pkgs; [btrfs-progs coreutils gnused util-linux];

        serviceConfig = {
          Type = "oneshot";
        };

        script = ''
          mkdir -p /mnt
          mount -o subvolid=5 /dev/disk/by-label/root /mnt

          delete_subvolume_recursively() {
            local subvol="$1"
            local nested
            while IFS= read -r nested; do
              [ -n "$nested" ] && delete_subvolume_recursively "/mnt/$nested"
            done < <(btrfs subvolume list -o "$subvol" | sed -n 's/.*path //p')

            echo "Deleting subvolume $subvol..."
            btrfs subvolume delete "$subvol"
          }

          if [ -e /mnt/@root ]; then
            delete_subvolume_recursively /mnt/@root
          fi

          echo "Restoring blank /@root subvolume..."
          btrfs subvolume snapshot /mnt/@root-blank /mnt/@root

          umount /mnt
        '';
      };
    };
  };

  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-label/root";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
      "ssd"
      "subvol=@root"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/root";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
      "ssd"
      "subvol=@nix"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-label/root";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd:5"
      "discard=async"
      "space_cache=v2"
      "ssd"
      "subvol=@persist"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-label/swap";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
