# inputs
[nixpkgs]
src.git = "https://github.com/NixOS/nixpkgs"
src.branch = "nixos-unstable"
fetch.github = "NixOS/nixpkgs"

[preservation]
src.git = "https://github.com/nix-community/preservation"
fetch.github = "nix-community/preservation"

[sops-nix]
src.git = "https://github.com/Mic92/sops-nix"
fetch.github = "Mic92/sops-nix"

[hjem]
src.git = "https://github.com/feel-co/hjem"
fetch.github = "feel-co/hjem"

[quickshell]
src.git = "https://github.com/quickshell-mirror/quickshell"
fetch.github = "quickshell-mirror/quickshell"
pinned = true

[emacs]
src.git = "https://git.gay/sunworms/emacs-config"
fetch.git = "https://git.gay/sunworms/emacs-config"

# binary packages
[eden-nightly]
src.github_tag = "Eden-CI/Nightly"
src.from_pattern = 'v(\d+)\.([a-f0-9]+)'
src.to_pattern = 'v\1.\2/Eden-Linux-\2'
fetch.url = "https://github.com/Eden-CI/Nightly/releases/download/$ver-amd64-clang-pgo.AppImage"

[pcsx2]
src.github_tag = "pcsx2/pcsx2"
fetch.url = "https://github.com/PCSX2/pcsx2/releases/download/$ver/pcsx2-$ver-linux-appimage-x64-Qt.AppImage"

[helium]
src.github = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"