[audio]
enable_overdrive = true

[calendar]
enabled = true

    [calendar.account.personal_google]
    color = "primary"
    name = "Sunny's calendar"
    type = "google"

[osd]
background_opacity = 0.9

[bar]
order = [ "default", "right" ]

    [bar.right]
    auto_hide = true
    background_opacity = 0.9
    center = []
    enabled = true
    margin_ends = 0
    position = "right"
    radius = 0
    radius_bottom_left = 10
    radius_top_left = 10
    start = [ "taskbar" ]
    end = [ "group:net", "group:notif", "group:mpv" ]
    thickness = 30

        [[bar.right.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "net"
        members = [ "network", "bluetooth" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

        [[bar.right.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "notif"
        members = [ "notifications", "clipboard" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

        [[bar.right.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "mpv"
        members = [ "mpvpaper", "colorpicker" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

    [bar.default]
    background_opacity = 0.9
    capsule = true
    capsule_opacity = 0.9
    capsule_radius = 8.0
    end = [ "tray", "group:sysmon", "group:osd" ]
    center = [ "workspaces" ]
    start = [ "group:misc", "clock", "group:music" ]
    position = "left"
    widget_spacing = 10
    margin_edge = 0
    margin_ends = 0
    radius = 0
    radius_bottom_right = 10
    radius_top_right = 10
    scale = 1.0
    shadow = false
    thickness = 30
    attach_panels = true

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "sysmon"
        members = [ "cpu", "ram", "temp" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "osd"
        members = [ "volume", "brightness", "battery" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "music"
        members = [ "media", "cat" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "misc"
        members = [ "launcher", "recorder", "wallpaper" ]
        opacity = 0.9
        padding = 6.0
        radius = 8.0

[idle]
behavior_order = [ "idle-behavior", "idle-behavior-2" ]

    [idle.behavior.idle-behavior]
    action = "lock"
    enabled = true
    timeout = 300

    [idle.behavior.idle-behavior-2]
    action = "screen_off"
    enabled = true
    timeout = 600

[location]
auto_locate = false

[dock]
auto_hide = true
background_opacity = 0.9
enabled = false
position = "top"

[notification]
background_opacity = 0.9

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "login-box",
    "logout",
    "shutdown",
    "reboot",
    "suspend",
    "media",
    "clock",
    "weather",
    "sysmon"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."login-box"]
    box_height = 70.0
    box_width = 400.0
    cx = 823.0
    cy = 910.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget.logout]
    box_height = 48.0
    box_width = 48.0
    cx = 727.0
    cy = 986.5
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.logout.settings]
        background = true
        command = "noctalia msg session logout"
        glyph = "logout"
        variant = "default"

    [lockscreen_widgets.widget.shutdown]
    box_height = 48.0
    box_width = 48.0
    cx = 919.0
    cy = 986.5
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.shutdown.settings]
        background = true
        command = "noctalia msg session shutdown"
        glyph = "shutdown"
        variant = "default"

    [lockscreen_widgets.widget.reboot]
    box_height = 48.0
    box_width = 48.0
    cx = 855.0
    cy = 986.5
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.reboot.settings]
        background = true
        command = "noctalia msg session reboot"
        glyph = "reboot"
        variant = "default"

    [lockscreen_widgets.widget.suspend]
    box_height = 48.0
    box_width = 48.0
    cx = 791.0
    cy = 986.5
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.suspend.settings]
        background = true
        command = "noctalia msg session lock-and-suspend"
        glyph = "suspend"
        variant = "default"

    [lockscreen_widgets.widget.media]
    box_height = 192.0
    box_width = 384.0
    cx = 823.0
    cy = 498.5
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.clock]
    box_height = 128.0
    box_width = 208.0
    cx = 823.0
    cy = 726.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.clock.settings]
        center_text = true
        clock_style = "digital"
        format = "{:%H:%M\\n%a, %b %d}"

    [lockscreen_widgets.widget.weather]
    box_height = 128.0
    box_width = 208.0
    cx = 1063.0
    cy = 726.5
    output = "eDP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.weather.settings]
        forecast_days = 2
        show_forecast = true

    [lockscreen_widgets.widget.sysmon]
    box_height = 0.0
    box_width = 0.0
    cx = 587.0
    cy = 725.5
    output = "eDP-1"
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.sysmon.settings]
        stat = "cpu_usage"
        stat2 = "ram_pct"

[shell]
avatar_path = "/home/sunny/.face"
clipboard_auto_paste = "off"
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false
clipboard_image_action_command = "satty -f -"

    [shell.panel]
    transparency_mode = "glass"
    clipboard_placement = "attached"
    launcher_placement = "attached"
    attach_session = true

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "pkill noctalia && noctalia -d"
    enabled = true
    glyph = "noctalia"
    label = "Restart Noctalia"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    variant = "default"

[theme]
builtin = "Noctalia"
source = "wallpaper"
wallpaper_scheme = "faithful"
community_palette = "GruvboxAlt"

    [theme.templates]
    builtin_ids = [ "foot", "gtk3", "gtk4", "helix", "niri", "kcolorscheme", "qt" ]
    community_ids = [ ]

    [theme.templates.user.nvim-base16]
    input_path = "~/.config/noctalia/templates/matugen-template.lua"
    output_path = "~/.config/matugen/neovim.lua"
    post_hook = 'pkill -SIGUSR1 nvim'
    
    [theme.templates.user.zathura]
    input_path = "~/.config/noctalia/templates/zathurarc"
    output_path = '~/.config/zathura/zathurarc'

[wallpaper]
directory = "/home/sunny/Pictures/walls"

    [widget.clock]
    format = "{:%a:%m:%d:%H:%M}"
    vertical_format = "{:%d\\n%m\\n-\\n%H\\n%M}"

    [widget.taskbar]
    capsule = true
    group_by_workspace = true

    [widget.network]
    show_label = false

    [widget.workspaces]
    display = "none"

    [widget.cpu]
    display = "gauge"
    show_label = false
    type = "sysmon"

    [widget.ram]
    display = "gauge"
    show_label = false
    stat = "ram_used"
    type = "sysmon"

    [widget.temp]
    show_label = false
    stat = "cpu_temp"
    type = "sysmon"
    
    [widget.brightness]
    show_label = false

    [widget.volume]
    show_label = false

    [widget.recorder]
    type = "noctalia/screen_recorder:recorder"

    [widget.cat]
    audio_spectrum = true
    tappy_mode = true
    type = "noctalia/bongocat:cat"
    use_mpris_filter = true

    [widget.launcher]
    glyph = "niri"
    custom_image = @NIXOS_IMAGE@
    custom_image_colorize = true

    [widget.media]
    max_length = 150
    title_scroll = "on_hover"

    [widget.mpvpaper]
    type = "noctalia/mpvpaper:mpvpaper"
    
    [widget.colorpicker]
    type = "oldirtty/color_picker:colorpicker"
    
[battery]
warning_threshold = 20

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/home/sunny/Pictures/walls/videos"

[plugin_settings."oldirtty/color_picker"]
hyprpicker-lowercase = true

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/kaomoji", "noctalia/bongocat", "noctalia/mpvpaper", "oldirtty/color_picker" ]
