[audio]
enable_overdrive = true

[bar.default]
background_opacity = 0.9
capsule = true
capsule_groups = [ "mpris", "wifi-bt", "sysmon", "vol-bright-bat" ]
capsule_opacity = 0.9
end = [ "tray", "notifications", "network", "bluetooth", "cpu", "ram", "temp", "volume", "brightness", "battery" ]
position = "bottom"
start = [ "launcher", "wallpaper", "workspaces", "media", "audio_visualizer" ]
widget_spacing = 10
margin_edge = 0
margin_ends = 120
radius = 16
radius_bottom_left = 0
radius_bottom_right = 0
scale = 1.0
shadow = false
thickness = 30
attach_panels = true

[idle.behavior.lock]
timeout = 300
command = "noctalia:screen-lock"
enabled = true

[idle.behavior.screen-off]
timeout = 600
command = "noctalia:dpms-off"
resume_command = "noctalia:dpms-on"

[dock]
auto_hide = true
background_opacity = 0.9
enabled = false
position = "top"

[notification]
background_opacity = 0.9

[shell]
avatar_path = "/home/sunny/nixos-files/assets/icons/haruta.jpg"
clipboard_auto_paste = "off"
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false

[theme]
builtin = "Noctalia"
source = "wallpaper"
wallpaper_scheme = "faithful"
community_palette = "GruvboxAlt"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "helix", "kcolorscheme", "niri", "kitty" ]
    community_ids = [ "discord" ]
    enable_user_templates = false

[wallpaper]
directory = "/home/sunny/Pictures/walls"

[weather]
address = "Jatani, India"

[widget.clock]
format = "{:%a, %b %d, %H:%M}"

[widget.network]
show_label = false
capsule_group = "wifi-bt"

[widget.workspaces]
display = "none"

[widget.cpu]
display = "gauge"
show_label = false
type = "sysmon"
capsule_group = "sysmon"

[widget.ram]
display = "gauge"
show_label = false
stat = "ram_used"
type = "sysmon"
capsule_group = "sysmon"

[widget.temp]
show_label = false
stat = "cpu_temp"
type = "sysmon"
capsule_group = "sysmon"

[widget.audio_visualizer]
capsule_group = "mpris"

[widget.battery]
capsule_group = "vol-bright-bat"

[widget.bluetooth]
capsule_group = "wifi-bt"

[widget.brightness]
capsule_group = "vol-bright-bat"

[widget.media]
capsule_group = "mpris"

[widget.volume]
capsule_group = "vol-bright-bat"

[hooks]
battery_low_percent_threshold = 20

[shell.panel]
attach_clipboard = true
attach_launcher = true
