-- Generated by Matugen

require("base16-colorscheme").setup({
	-- Background & UI Tones
	base00 = "{{colors.surface.default.hex}}", -- Default Background
	base01 = "{{colors.surface_container_low.default.hex}}", -- Lighter Background
	base02 = "{{colors.surface_container.default.hex}}", -- Selection Background (for text)
	base03 = "{{colors.outline.default.hex}}", -- Comments / Invisibles

	-- Foreground Tones
	base04 = "{{colors.on_surface_variant.default.hex}}", -- Dark Foreground
	base05 = "{{colors.on_surface.default.hex}}", -- Default Foreground
	base06 = "{{colors.inverse_on_surface.default.hex}}", -- Light Foreground
	base07 = "{{colors.surface_bright.default.hex}}", -- Lightest Foreground

	-- Accent Colors (Mapping to high-saturation roles)
	base08 = "{{colors.error.default.hex}}", -- Variables/Errors (Red)
	base09 = "{{colors.tertiary.default.hex}}", -- Integers/Constants (Usually the '3rd' accent)
	base0A = "{{colors.secondary_fixed.default.hex}}", -- Classes/Search (Using 'fixed' for more 'pop')
	base0B = "{{colors.primary.default.hex}}", -- Strings/Green-ish (The most vibrant role)
	base0C = "{{colors.primary_fixed.default.hex}}", -- Regex/Escape
	base0D = "{{colors.secondary.default.hex}}", -- Functions/Methods
	base0E = "{{colors.inverse_primary.default.hex}}", -- Keywords/Storage (High contrast)
	base0F = "{{colors.tertiary_fixed.default.hex | lighten: -10}}", -- Deprecated
})

-- Manual overrides to maximize color separation
local function set_hl_multiple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- 1. Keywords (The "Pop" color)
set_hl_multiple({ "Keyword", "TSKeyword", "TSRepeat", "Statement" }, {
	fg = "{{colors.inverse_primary.default.hex}}",
	bold = true,
})

-- 2. Strings (Highly visible)
set_hl_multiple({ "String", "TSString" }, {
	fg = "{{colors.primary.default.hex}}",
})

-- 3. Functions
set_hl_multiple({ "TSMethod", "Function", "TSFunction" }, {
	fg = "{{colors.secondary.default.hex}}",
})

-- 4. Constants & Numbers
set_hl_multiple({ "Number", "Boolean", "Float", "Constant" }, {
	fg = "{{colors.tertiary.default.hex}}",
})

-- 5. Visual Selection (Use a Container color for the background ONLY)
vim.api.nvim_set_hl(0, "Visual", {
	bg = "{{colors.primary_container.default.hex}}",
	fg = "{{colors.on_primary_container.default.hex}}",
})

-- 6. UI Polish
vim.api.nvim_set_hl(0, "LineNr", {
	fg = "{{colors.outline.default.hex}}",
})

vim.api.nvim_set_hl(0, "CursorLine", {
	bg = "{{colors.surface_container_highest.default.hex}}",
})

set_hl_multiple({ "Delimiter", "TSDelimiter", "TSPunctDelimiter" }, {
	fg = "{{colors.primary.default.hex}}", -- Or pick another accent like secondary
})

set_hl_multiple({ "TSPunctBracket", "bracket" }, {
	fg = "{{colors.on_surface_variant.default.hex}}", -- Usually better as a subtle foreground color
})

set_hl_multiple({ "Operator", "TSOperator" }, {
	fg = "{{colors.secondary.default.hex}}", -- High contrast for logic gates
	bold = true,
})
