[config]
version_check = false
fallback_color = "#ffbf9b"
prefer = "closest-to-fallback"
caching = false
expr_prefix = "{{"
expr_postfix = "}}"
block_prefix = "<*"
block_postfix = "*>"
contrast = 1.0
source_color_index = 0

[config.wallpaper]
set = true
command = "awww img --transition-type none {{ image }}"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/colors.ini"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = '''
dconf write /org/gnome/desktop/interface/gtk-theme "''"
dconf write /org/gnome/desktop/interface/gtk-theme "'adw-gtk3'"
'''

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'apply-gtk4-theme'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "pkill -SIGUSR1 kitty"

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/config'
post_hook = 'makoctl reload'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.neovim]
input_path = "~/.config/matugen/templates/vim-colors.vim"
output_path = "~/.config/matugen/themes/colors.vim"
post_hook = "pkill -SIGUSR1 nvim"

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill waybar && waybar -c ~/.config/waybar/config-1.jsonc > /dev/null 2>&1 & waybar -c ~/.config/waybar/config-2.jsonc > /dev/null 2>&1 &"

[templates.yazi]
input_path = "~/.config/matugen/templates/yazi.toml"
output_path = "~/.config/yazi/flavors/matugen.yazi/flavor.toml"

[templates.yazi-syntax]
input_path = "~/.config/matugen/templates/yazi.tmTheme"
output_path = "~/.config/yazi/flavors/matugen.yazi/tmtheme.xml"

[templates.zathura]
input_path = "~/.config/matugen/templates/zathurarc"
output_path = "~/.config/zathura/zathurarc"
post_hook = '''
set -l zathura_instances (dbus-send --session \
    --dest=org.freedesktop.DBus \
    --type=method_call \
    --print-reply \
    /org/freedesktop/DBus \
    org.freedesktop.DBus.ListNames | \
    string match -r 'org\.pwmt\.zathura\.PID-[0-9]+')

for id in $zathura_instances
    dbus-send --session \
        --dest="$id" \
        --type=method_call \
        /org/pwmt/zathura \
        org.pwmt.zathura.ExecuteCommand \
        string:"source"
end
'''

