rootcolor={{colors.background.dark.hex_stripped}}cc

bordercolor={{colors.outline_variant.dark.hex_stripped}}cc

focuscolor={{colors.primary.dark.hex_stripped}}cc

urgentcolor={{colors.error.dark.hex_stripped}}cc

scratchpadcolor={{colors.tertiary.dark.hex_stripped}}cc

globalcolor={{colors.secondary_container.dark.hex_stripped}}cc

overlaycolor={{colors.tertiary_container.dark.hex_stripped}}cc
