[config]

[templates]
[templates.neovim]
input_path = '~/.config/matugen/template.lua'
output_path = '~/.config/nvim/base16.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.spicetify]
input_path = '~/.config/matugen/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'

[templates.zathura]
input_path = '~/.config/matugen/zathura-colors'
output_path = '~/.config/zathura/zathurarc'
