[config]

[templates]
[templates.vesktop]
input_path = '~/.config/matugen/vesktop.css'
output_path = '~/.config/matugen/midnight-discord.css'

#[templates.zathura]
#input_path = '~/.config/matugen/zathura-colors'
#output_path = '~/.config/zathura/zathurarc'
